package net.emsee.thedungeon.dungeon.registry.roomCollections;

import net.emsee.thedungeon.dungeon.src.types.grid.room.GridRoomBasic;
import net.emsee.thedungeon.dungeon.src.Connection;
import net.emsee.thedungeon.dungeon.src.types.grid.roomCollection.GridRoomCollection;

public final class TestGridRoomCollection extends GridRoomCollection {
        public TestGridRoomCollection() {
                super(3, 3);
                this.setFallback(GridRoomBasic.builder("test/fallback", 3, 3).build())
                        .addRoom(GridRoomBasic.builder("test/x", 3, 3)
                                .withWeight(1)
                                .horizontalConnections()
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/i", 3, 3)
                                .withWeight(1)
                                .addConnection(Connection.NORTH).addConnection(Connection.SOUTH)
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/t", 3, 3)
                                .withWeight(1)
                                .addConnection(Connection.NORTH).addConnection(Connection.SOUTH).addConnection(Connection.WEST)
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/d", 3, 3)
                                .withWeight(1)
                                .addConnection(Connection.DOWN)
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/lr", 3, 3)
                                .setSize(3, 1)
                                .withWeight(1)
                                .horizontalConnections()
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/lro", 3, 3)
                                .setSize(3, 1)
                                .setHorizontalConnectionOffset(Connection.WEST, 1, 0)
                                .withWeight(1)
                                .addConnection(Connection.WEST)
                                .doAllowRotation().build()
                        )
                        .addRoom(GridRoomBasic.builder("test/lrou", 3, 3)
                                .setSize(3, 1)
                                .setVerticalConnectionOffset(Connection.UP, 1, 0)
                                .withWeight(1)
                                .addConnection(Connection.UP)
                                .horizontalConnections()
                                .doAllowRotation(true, true).build()
                        )
                        .addRoom(GridRoomBasic.builder("test/lrod", 3, 3)
                                .setSize(3, 1)
                                .setVerticalConnectionOffset(Connection.DOWN, -1, 0)
                                .withWeight(1)
                                .addConnection(Connection.DOWN)
                                .doAllowRotation(true, true).build()
                        )
                        .addRoom(GridRoomBasic.builder("test/tag", 3, 3)
                                .withWeight(1)
                                .setConnectionTag(Connection.NORTH, "stone")
                                .doAllowRotation()
                                .addConnection(Connection.NORTH)
                                .addConnection(Connection.SOUTH).build()
                        );
        }
}
